### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by own2pwn** [Razzile/HackyMachy#1]
What should I link to get rid out of fucking `mach_exc_server` undefined symbol?

**Comment by Razzile** [comment]
it's defined here https://github.com/Razzile/HackyMachy/blob/76518c4048d8565d6ac25a45eb2d01eb9d2f97b1/SwiftDebugTest/mach_excServer.c#L759

but this "project" is completely useless and i don't know why you would want to build it anyway

**Comment by own2pwn** [comment]
I think I'm missing smth. because Xcode complains to this one
<img width="819" alt="default" src="https://user-images.githubusercontent.com/7850039/37113254-e82bbe1c-2255-11e8-891d-de608c9ee074.png">

I've cloned it and tried to run. I wanted to play a bit with Mach EXC handling but Xcode won't compile it any way. I've tried to find any docs about how to use mig (and finally found!). So then I generated defs, but xcode still can't find symbols for `catch_mach_exception_raise` and other.

Am I missing something?

**Comment by Razzile** [comment]
xcode is listing the .c files in the project for compilation right?

**Comment by own2pwn** [comment]
Yup, it does
<img width="422" alt="default" src="https://user-images.githubusercontent.com/7850039/37113823-937f7c1c-2257-11e8-9e97-eea3e2c68868.png">

**Comment by Razzile** [comment]
add mach_excServer.c to that too

**Comment by own2pwn** [comment]
Really stupid of me! Sorry, I thought all the needed sources are included in project so they would be in a compilation phase

**Comment by Razzile** [comment]
no worries, hope it helps you in your research
